openapi: 3.0.3
info:
  title: API de Productos
  description: API para gestionar productos
  version: 1.0.0
servers:
- url: http://localhost:8082/
  description: Servidor local de desarrollo
paths:
  /productos:
    get:
      summary: Obtener todos los productos
      operationId: productos_get
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.product_controller
    post:
      summary: Crear un nuevo producto
      operationId: producto_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Producto"
        required: true
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /producto/{id}:
    get:
      summary: Obtener un producto por su id
      operationId: producto_id_get
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "404":
          description: Producto no encontrado
      x-openapi-router-controller: swagger_server.controllers.product_controller
    put:
      summary: Actualizar un producto por ID
      operationId: productos_id_put
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Producto"
        required: true
      responses:
        "200":
          description: Producto actualizado correctamente
      x-openapi-router-controller: swagger_server.controllers.product_controller
    delete:
      summary: Eliminar un producto por ID
      operationId: producto_id_delete
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Producto eliminado correctamente
      x-openapi-router-controller: swagger_server.controllers.product_controller
components:
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nombre:
          type: string
          example: Producto
        precio:
          type: integer
          example: 2
        stock:
          type: integer
          example: 1
        descripcion:
          type: string
          example: descripcion
      example:
        descripcion: descripcion
        precio: 2
        id: 1
        stock: 1
        nombre: Producto

